# Generated by Django 5.0.1 on 2024-02-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_desi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desi_name', models.CharField(max_length=50)),
            ],
        ),
    ]
