# Generated by Django 5.0.1 on 2024-02-14 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basics', '0002_tbl_desi'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_contact', models.CharField(max_length=50)),
                ('emp_email', models.CharField(max_length=50)),
                ('emp_basal', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Basics.tbl_dept')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Basics.tbl_desi')),
            ],
        ),
    ]
