# Generated by Django 5.0.1 on 2024-02-14 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basics', '0003_tbl_emp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_emp',
            old_name='department',
            new_name='dept',
        ),
        migrations.RenameField(
            model_name='tbl_emp',
            old_name='designation',
            new_name='desi',
        ),
    ]
