# Generated by Django 5.0.1 on 2024-02-19 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basics', '0006_tbl_semster_tbl_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_semster',
            new_name='tbl_semester',
        ),
    ]
