# Generated by Django 5.0.1 on 2024-02-19 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basics', '0007_rename_tbl_semster_tbl_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_semester',
            old_name='semster_no',
            new_name='semester_no',
        ),
    ]
