# Generated by Django 5.0.1 on 2024-02-19 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basics', '0008_rename_semster_no_tbl_semester_semester_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Basics.tbl_course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Basics.tbl_semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Basics.tbl_subject')),
            ],
        ),
    ]
