# Generated by Django 5.0.1 on 2024-02-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_typepot'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_shapepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_name', models.CharField(max_length=50)),
            ],
        ),
    ]
