# Generated by Django 5.0.1 on 2024-02-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_nurserystaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurserystaff_name', models.CharField(max_length=50)),
                ('nurserystaff_gender', models.CharField(max_length=50)),
                ('nurserystaff_contact', models.CharField(max_length=50)),
                ('nurserystaff_email', models.CharField(max_length=50)),
                ('nurserystaff_password', models.CharField(max_length=50)),
            ],
        ),
    ]
