# Generated by Django 5.0.1 on 2024-02-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_nurserystaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_deliverystaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverystaff_name', models.CharField(max_length=50)),
                ('deliverystaff_gender', models.CharField(max_length=50)),
                ('deliverystaff_contact', models.CharField(max_length=50)),
                ('deliverystaff_email', models.CharField(max_length=50)),
                ('deliverystaff_password', models.CharField(max_length=50)),
            ],
        ),
    ]
