# Generated by Django 5.0.1 on 2024-02-22 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_productplant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productplant_name', models.CharField(max_length=50)),
                ('productplant_description', models.CharField(max_length=50)),
                ('productplant_rate', models.CharField(max_length=50)),
                ('productplant_stock', models.CharField(max_length=50)),
                ('productplant_image', models.FileField(upload_to='Assets/UserPhoto/')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subcategory')),
            ],
        ),
    ]
