# Generated by Django 5.0.1 on 2024-02-26 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_galleryplant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='galleryplant',
        ),
    ]
