# Generated by Django 5.0.1 on 2024-02-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_tbl_galleryplant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_productplant',
            name='productplant_image',
            field=models.FileField(upload_to='Assets/ProductPlantPhoto/'),
        ),
        migrations.DeleteModel(
            name='tbl_galleryplant',
        ),
    ]
