# Generated by Django 5.0.1 on 2024-02-26 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0017_alter_tbl_productplant_productplant_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_galleryplant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galleryplant_file', models.FileField(upload_to='Assets/GalleryPlantPhoto/')),
                ('galleryplant_description', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_productplant')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subcategory')),
            ],
        ),
    ]
