# Generated by Django 5.0.1 on 2024-03-01 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0018_tbl_galleryplant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_admin',
        ),
    ]
