# Generated by Django 5.0.1 on 2024-03-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0019_delete_tbl_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=50)),
                ('admin_contact', models.CharField(max_length=50)),
                ('admin_email', models.CharField(max_length=50)),
                ('admin_password', models.CharField(max_length=50)),
                ('admin_photo', models.FileField(upload_to='Assets/AdminPhoto/')),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_deliverystaff',
        ),
        migrations.DeleteModel(
            name='tbl_nurserystaff',
        ),
    ]
