# Generated by Django 5.0.1 on 2024-03-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0020_tbl_admin_delete_tbl_deliverystaff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_deliverystaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverystaff_name', models.CharField(max_length=50)),
                ('deliverystaff_gender', models.CharField(max_length=50)),
                ('deliverystaff_contact', models.CharField(max_length=50)),
                ('deliverystaff_email', models.CharField(max_length=50)),
                ('deliverystaff_password', models.CharField(max_length=50)),
                ('deliverystaff_photo', models.FileField(upload_to='Assets/DeliveryPhoto/')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_nurserystaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurserystaff_name', models.CharField(max_length=50)),
                ('nurserystaff_gender', models.CharField(max_length=50)),
                ('nurserystaff_contact', models.CharField(max_length=50)),
                ('nurserystaff_email', models.CharField(max_length=50)),
                ('nurserystaff_password', models.CharField(max_length=50)),
                ('nurserystaff_photo', models.FileField(upload_to='Assets/NurseryPhoto/')),
            ],
        ),
    ]
