# Generated by Django 5.0.1 on 2024-03-04 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0021_tbl_deliverystaff_tbl_nurserystaff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_productplant',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='tbl_galleryplant',
        ),
        migrations.DeleteModel(
            name='tbl_productplant',
        ),
    ]
