# Generated by Django 5.0.1 on 2024-03-11 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0023_tbl_productplant_tbl_galleryplant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_galleryplant',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='tbl_productplant',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='tbl_subcategory',
        ),
    ]
