# Generated by Django 5.0.1 on 2024-03-11 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0024_remove_tbl_galleryplant_subcategory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_galleryplant',
        ),
        migrations.DeleteModel(
            name='tbl_productplant',
        ),
    ]
