# Generated by Django 5.0.1 on 2024-03-11 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0025_delete_tbl_galleryplant_delete_tbl_productplant'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_productplant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productplant_name', models.CharField(max_length=50)),
                ('productplant_description', models.CharField(max_length=50)),
                ('productplant_rate', models.CharField(max_length=50)),
                ('productplant_stock', models.CharField(max_length=50)),
                ('productplant_image', models.FileField(upload_to='Assets/ProductPlantPhoto/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_category')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_galleryplant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galleryplant_file', models.FileField(upload_to='Assets/GalleryPlantPhoto/')),
                ('galleryplant_description', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_productplant')),
            ],
        ),
    ]
