# Generated by Django 5.0.1 on 2024-03-11 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0026_tbl_productplant_tbl_galleryplant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_productplant',
            name='category',
        ),
        migrations.DeleteModel(
            name='tbl_galleryplant',
        ),
        migrations.DeleteModel(
            name='tbl_productplant',
        ),
    ]
