# Generated by Django 5.0.1 on 2024-03-04 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NurseryStaff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_productplant',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='tbl_galleryplant',
        ),
        migrations.DeleteModel(
            name='tbl_productplant',
        ),
    ]
