# Generated by Django 5.0.1 on 2024-03-19 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0028_tbl_subcategory'),
        ('NurseryStaff', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_productpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productpot_name', models.CharField(max_length=50)),
                ('productpot_description', models.CharField(max_length=50)),
                ('productpot_rate', models.CharField(max_length=50)),
                ('productpot_stock', models.CharField(max_length=50)),
                ('productpot_image', models.FileField(upload_to='Assets/ProductPotPhoto/')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_colorpot')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_materialpot')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_shapepot')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_sizepot')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_typepot')),
            ],
        ),
    ]
