# Generated by Django 5.0.1 on 2024-03-19 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NurseryStaff', '0004_tbl_productpot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_productplant',
            name='category',
        ),
        migrations.DeleteModel(
            name='tbl_galleryplant',
        ),
        migrations.DeleteModel(
            name='tbl_productplant',
        ),
    ]
