# Generated by Django 5.0.1 on 2024-03-19 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0028_tbl_subcategory'),
        ('NurseryStaff', '0005_remove_tbl_productplant_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_productplant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productplant_name', models.CharField(max_length=50)),
                ('productplant_description', models.CharField(max_length=50)),
                ('productplant_rate', models.CharField(max_length=50)),
                ('productplant_stock', models.CharField(max_length=50)),
                ('productplant_image', models.FileField(upload_to='Assets/ProductPlantPhoto/')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_galleryplant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galleryplant_file', models.FileField(upload_to='Assets/GalleryPlantPhoto/')),
                ('galleryplant_description', models.CharField(max_length=50)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subcategory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NurseryStaff.tbl_productplant')),
            ],
        ),
    ]
