# Generated by Django 5.0.1 on 2024-03-20 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NurseryStaff', '0007_tbl_gallerypot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_gallerypot',
        ),
    ]
