# Generated by Django 5.0.1 on 2024-03-20 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NurseryStaff', '0008_delete_tbl_gallerypot'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_gallerypot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallerypot_file', models.FileField(upload_to='Assets/GalleryPotPhoto/')),
                ('gallerypot_description', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NurseryStaff.tbl_productpot')),
            ],
        ),
    ]
