# Generated by Django 5.0.1 on 2024-04-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NurseryStaff', '0009_tbl_gallerypot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_productplant',
            name='productplant_stock',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_productpot',
            name='productpot_stock',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
