# Generated by Django 5.0.1 on 2024-04-04 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NurseryStaff', '0010_alter_tbl_productplant_productplant_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_productplant',
            name='productplant_stock',
        ),
    ]
