# Generated by Django 5.0.1 on 2024-04-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NurseryStaff', '0012_tbl_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_productplant',
            name='productplant_stock',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
