# Generated by Django 5.0.1 on 2024-04-09 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NurseryStaff', '0013_tbl_productplant_productplant_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_galleryplant',
            name='galleryplant_description',
        ),
        migrations.RemoveField(
            model_name='tbl_gallerypot',
            name='gallerypot_description',
        ),
    ]
