# Generated by Django 5.0.1 on 2024-04-17 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NurseryStaff', '0014_remove_tbl_galleryplant_galleryplant_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_productplant',
            name='productplant_stock',
        ),
    ]
