# Generated by Django 5.0.1 on 2024-04-18 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NurseryStaff', '0015_remove_tbl_productplant_productplant_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_stock',
            new_name='tbl_stockplant',
        ),
    ]
