# Generated by Django 5.0.1 on 2024-04-18 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NurseryStaff', '0016_rename_tbl_stock_tbl_stockplant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_stockplant',
            name='productplant',
        ),
    ]
