# Generated by Django 5.0.1 on 2024-04-18 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NurseryStaff', '0017_remove_tbl_stockplant_productplant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_stockplant',
        ),
    ]
