# Generated by Django 5.0.1 on 2024-04-18 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NurseryStaff', '0018_delete_tbl_stockplant'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_stockplant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.IntegerField()),
                ('stock_date', models.DateField(null=True)),
                ('productplant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NurseryStaff.tbl_productplant')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_stockpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.IntegerField()),
                ('stock_date', models.DateField(null=True)),
                ('productpot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NurseryStaff.tbl_productpot')),
            ],
        ),
    ]
