# Generated by Django 5.0.1 on 2024-04-19 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NurseryStaff', '0019_tbl_stockplant_tbl_stockpot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_productpot',
            name='productpot_stock',
        ),
    ]
