# Generated by Django 5.0.1 on 2024-02-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0004_tbl_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=50)),
            ],
        ),
    ]
