# Generated by Django 5.0.1 on 2024-02-27 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0005_tbl_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_player',
        ),
    ]
