# Generated by Django 5.0.1 on 2024-02-27 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0006_delete_tbl_player'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_position',
        ),
    ]
