# Generated by Django 5.0.1 on 2024-02-27 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0007_delete_tbl_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=50)),
                ('player_image', models.FileField(upload_to='Assets/TestPhoto/')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.tbl_team')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.tbl_position')),
            ],
        ),
    ]
