# Generated by Django 5.0.1 on 2024-02-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0008_tbl_position_tbl_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(max_length=50)),
                ('schedule_fromdate', models.CharField(max_length=50)),
                ('schedule_duedate', models.CharField(max_length=50)),
                ('schedule_venue', models.CharField(max_length=50)),
            ],
        ),
    ]
