# Generated by Django 5.0.1 on 2024-03-06 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='user_status',
        ),
    ]
