# Generated by Django 5.0.1 on 2024-03-13 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_remove_tbl_user_user_status'),
        ('User', '0009_remove_tbl_complaint_user_remove_tbl_feedback_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
