# Generated by Django 5.0.1 on 2024-03-05 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
