# Generated by Django 5.0.1 on 2024-03-13 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_tbl_complaint_complaint_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_feedback',
            name='user',
        ),
    ]
