# Generated by Django 5.0.1 on 2024-03-19 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_remove_tbl_complaint_user_remove_tbl_feedback_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
        migrations.DeleteModel(
            name='tbl_feedback',
        ),
    ]
