# Generated by Django 5.0.1 on 2024-03-19 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0008_initial'),
        ('User', '0010_delete_tbl_complaint_delete_tbl_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=150)),
                ('complaint_details', models.CharField(max_length=500)),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('complaint_status', models.IntegerField(default='0')),
                ('complaint_reply', models.CharField(max_length=500, null=True)),
                ('complaint_replydate', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_subject', models.CharField(max_length=500)),
                ('feedback_details', models.CharField(max_length=500)),
                ('feedback_postdate', models.DateField(auto_now_add=True)),
                ('feedback_status', models.IntegerField(default='0')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
