# Generated by Django 5.0.1 on 2024-03-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_tbl_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_order',
        ),
    ]
