# Generated by Django 5.0.1 on 2024-03-22 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0028_tbl_subcategory'),
        ('Guest', '0008_initial'),
        ('NurseryStaff', '0009_tbl_gallerypot'),
        ('User', '0015_delete_tbl_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_deliverydate', models.DateField(null=True)),
                ('order_qty', models.CharField(max_length=50)),
                ('order_amount', models.CharField(max_length=50)),
                ('order_status', models.CharField(default='Confirmed', max_length=50)),
                ('order_address', models.CharField(max_length=500)),
                ('order_deliverycharge', models.CharField(max_length=50)),
                ('order_totalkm', models.CharField(max_length=50)),
                ('order_totalamount', models.CharField(max_length=50)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
                ('productplant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NurseryStaff.tbl_productplant')),
                ('productpot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NurseryStaff.tbl_productpot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
