# Generated by Django 5.0.1 on 2024-03-26 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_tbl_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_order',
            name='order_deliverycharge',
        ),
        migrations.RemoveField(
            model_name='tbl_order',
            name='order_totalamount',
        ),
        migrations.RemoveField(
            model_name='tbl_order',
            name='order_totalkm',
        ),
    ]
