# Generated by Django 5.0.1 on 2024-03-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_remove_tbl_order_order_deliverycharge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_order',
            name='order_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
