# Generated by Django 5.0.1 on 2024-03-31 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0028_tbl_subcategory'),
        ('User', '0018_alter_tbl_order_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_assigndelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_date', models.DateField(auto_now_add=True)),
                ('assign_status', models.IntegerField(default='0')),
                ('deliverystaff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_deliverystaff')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_order')),
            ],
        ),
    ]
