# Generated by Django 5.0.1 on 2024-03-31 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0028_tbl_subcategory'),
        ('User', '0019_tbl_assigndelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_assigndelivery',
            name='assign_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tbl_assigndelivery',
            name='deliverystaff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_deliverystaff'),
        ),
    ]
