# Generated by Django 5.0.1 on 2024-04-01 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_initial'),
        ('NurseryStaff', '0009_tbl_gallerypot'),
        ('User', '0020_alter_tbl_assigndelivery_assign_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlist_date', models.DateField(auto_now_add=True)),
                ('productplant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NurseryStaff.tbl_productplant')),
                ('productpot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NurseryStaff.tbl_productpot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
