# Generated by Django 5.0.1 on 2024-04-04 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NurseryStaff', '0013_tbl_productplant_productplant_stock'),
        ('User', '0022_tbl_productbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_qty', models.CharField(max_length=500)),
                ('cart_status', models.IntegerField(default='0')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_productbooking')),
                ('productplant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NurseryStaff.tbl_productplant')),
            ],
        ),
    ]
