# Generated by Django 5.0.1 on 2024-04-08 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_initial'),
        ('NurseryStaff', '0013_tbl_productplant_productplant_stock'),
        ('User', '0023_tbl_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_wishlistplant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlist_date', models.DateField(auto_now_add=True)),
                ('productplant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NurseryStaff.tbl_productplant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_wishlistpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlist_date', models.DateField(auto_now_add=True)),
                ('productpot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NurseryStaff.tbl_productpot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_wishlist',
        ),
    ]
