# Generated by Django 5.0.1 on 2024-04-18 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0024_tbl_wishlistplant_tbl_wishlistpot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_order',
            name='productplant',
        ),
    ]
