# Generated by Django 5.0.1 on 2024-04-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0025_remove_tbl_order_productplant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_cart',
            name='ship_status',
            field=models.IntegerField(default='0'),
        ),
    ]
