# Generated by Django 5.0.1 on 2024-04-25 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0026_tbl_cart_ship_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_feedback',
            name='user',
        ),
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
        migrations.DeleteModel(
            name='tbl_feedback',
        ),
    ]
