# Generated by Django 5.0.1 on 2024-04-25 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0028_tbl_complaint_tbl_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='product',
        ),
    ]
