# Generated by Django 5.0.1 on 2024-04-25 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_initial'),
        ('NurseryStaff', '0020_remove_tbl_productpot_productpot_stock'),
        ('User', '0029_remove_tbl_complaint_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rating', models.IntegerField(max_length=50)),
                ('user_review', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('review_datetime', models.DateTimeField(auto_now_add=True)),
                ('productplant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NurseryStaff.tbl_productplant')),
                ('productpot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NurseryStaff.tbl_productpot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_feedback',
        ),
    ]
