# Generated by Django 5.0.1 on 2024-05-02 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0030_tbl_review_delete_tbl_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_review',
            name='user',
        ),
    ]
