# Generated by Django 5.0.1 on 2024-05-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0031_remove_tbl_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_order',
            name='order_address',
        ),
        migrations.RemoveField(
            model_name='tbl_order',
            name='place',
        ),
        migrations.RemoveField(
            model_name='tbl_order',
            name='user',
        ),
        migrations.AlterField(
            model_name='tbl_order',
            name='order_status',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
