# Generated by Django 5.0.1 on 2024-05-06 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0032_remove_tbl_order_order_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_order',
            name='productpot',
        ),
        migrations.DeleteModel(
            name='tbl_assigndelivery',
        ),
        migrations.DeleteModel(
            name='tbl_order',
        ),
    ]
