# Generated by Django 5.0.1 on 2024-05-06 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0028_tbl_subcategory'),
        ('Guest', '0008_initial'),
        ('NurseryStaff', '0020_remove_tbl_productpot_productpot_stock'),
        ('User', '0033_remove_tbl_order_productpot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_deliverydate', models.DateField(null=True)),
                ('order_qty', models.CharField(max_length=50)),
                ('order_amount', models.CharField(max_length=50)),
                ('order_status', models.CharField(default='0', max_length=50)),
                ('productpot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NurseryStaff.tbl_productpot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_assigndelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_date', models.DateField(null=True)),
                ('assign_status', models.IntegerField(default='0')),
                ('deliverystaff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_deliverystaff')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_order')),
            ],
        ),
    ]
