# Generated by Django 5.0.1 on 2024-05-07 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0028_tbl_subcategory'),
        ('User', '0035_delete_tbl_assigndelivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_assigndelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_status', models.IntegerField(default='0')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_productbooking')),
                ('deliverystaff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_deliverystaff')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_order')),
            ],
        ),
    ]
