# Generated by Django 5.0.1 on 2024-05-07 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0036_tbl_assigndelivery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_assigndelivery',
        ),
    ]
