# Generated by Django 5.0.1 on 2024-05-07 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0028_tbl_subcategory'),
        ('User', '0037_delete_tbl_assigndelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_productbooking',
            name='assign_status',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tbl_productbooking',
            name='deliverystaff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_deliverystaff'),
        ),
    ]
